name: CICD

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
